#!/bin/bash
# This file was generated by Bin_Splitter.C
# ** source this file while in this directory

export SPINDIR=$(pwd)

export PHI_LOW=-3.150000
export PHI_HIGH=3.150000
export PHI_BINS=7
export PHI_DIV_0=-3.150000
export PHI_DIV_1=-2.250000
export PHI_DIV_2=-1.350000
export PHI_DIV_3=-0.450000
export PHI_DIV_4=0.450000
export PHI_DIV_5=1.350000
export PHI_DIV_6=2.250000
export PHI_DIV_7=3.150000

export ETA_LOW=2.500000
export ETA_HIGH=4.000000
export ETA_BINS=1
export ETA_DIV_0=2.500000
export ETA_DIV_1=4.000000

export PT_LOW=0.000000
export PT_HIGH=15.000000
export PT_BINS=11
export PT_DIV_0=0.000000
export PT_DIV_1=1.000000
export PT_DIV_2=1.500000
export PT_DIV_3=2.000000
export PT_DIV_4=2.500000
export PT_DIV_5=3.000000
export PT_DIV_6=3.500000
export PT_DIV_7=4.000000
export PT_DIV_8=5.000000
export PT_DIV_9=7.000000
export PT_DIV_10=10.000000
export PT_DIV_11=15.000000

export EN_LOW=0.000000
export EN_HIGH=250.000000
export EN_BINS=1
export EN_DIV_0=0.000000
export EN_DIV_1=250.000000
